print("Program starting.")
print("This is a program with simple menu where you can choose which operation the program performs.")
name1 = input("Before the menu, please insert your name: ")
print("")
print("Options:")
print("1 - Print welcome message")
print("2 - Print the name backwards")
print("3 - Print the first character")
print("4 - Show the amount of characters in the name")
print("0 - Exit")
choice = input("Your choice: ")
print ("Welcome", name1)
print("Program ending.")

